dist: trusty

sudo: true

python:
  - "3.4"

services:
  - docker
  - postgresql
  
language: python

install:
  - "make docker-test-image"
  
script:
  - "sudo -u postgres createuser root"
  - "sudo -u postgres psql -c 'alter user root with createdb;'"
  - "make docker-test-run"

