dist: trusty

sudo: true

python:
  - "3.4"

addons:
  apt:
    packages:
      - make
      - gcc
      - libboost-python-dev
      - libboost-system-dev
      - libboost-serialization-dev
      - libboost-iostreams-dev
      - libboost-thread-dev
      - libboost-program-options-dev
      - libpq-dev
      - libjsoncpp-dev
      # Disabling postgresql install becuase it breaks travis, but it is needed.
      # - postgresql

language: python

install:
  - "make init build"
  
script:
  - "make test"
